on:
  push:
#    paths:
#      - 'docs/**'
    branches:
      - master
name: Docs
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Generate Schema Docs
        run: |
          make -C docs schema
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          siteDir: /github/workspace/docs
